title: TREVOR J. FRANTZ
logo: /assets/images/me.png
show_downloads: false
theme: jekyll-theme-minimal
description: Software developer, Spiritual Christian, philosophical writer.<br><br>ğŸ“ <strong>Ohio, USA</strong><br>ğŸ‘” <strong><a href="https://www.linkedin.com/in/highverve/">LinkedIn</a></strong><br>ğŸ“§ <strong><a href="contact.html">Email Me</a></strong>
